apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: my-first-mlops-app
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://tfstate-dev-us-east-1-aj/model/churn_model.pkl
